version: '3.8'

services:
  server:
    build: ./server
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=production

  client:
    build: ./client
    ports:
      - '80:80'
    depends_on:
      - server
